version: "3.8"

services:
  #Это конфигурация Docker Compose для запуска веб-инструмента администрирования Authentik
  authentik-server:
    container_name: authentik-server
    command: server
    deploy:
      restart_policy:
        condition: always
        delay: 5s
    env_file: authentik.env
    image: ghcr.io/goauthentik/server:latest
    labels:
      com.centurylinklabs.watchtower.enable: "true"
      traefik.enable: "true"
      traefik.http.routers.authentik.entrypoints: "websecure"
      traefik.http.routers.authentik.rule: "Host(`authentik.${DOMAIN}`) || HostRegexp(`{subdomain:[a-z0-9]+}.${DOMAIN}`) && PathPrefix(`/outpost.goauthentik.io/`)"
      traefik.http.routers.authentik.service: "authentik"
      traefik.http.routers.authentik.tls.certresolver: "letsencrypt"
      traefik.http.services.authentik.loadbalancer.server.port: "9000"
    volumes:
      - "/mnt/docker-volumes/auth/src/media:/media"
      - "/mnt/docker-volumes/auth/src/templates:/templates"

networks:
  default:
    external: true
    name: $NETWORK
